"""Comprehensive tests for src/qa/graph/rule_upsert.py to improve coverage to 80%+."""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from src.qa.graph.rule_upsert import RuleUpsertManager


@pytest.fixture
def mock_graph_driver():
    """Mock Neo4j driver."""
    driver = MagicMock()
    session = MagicMock()
    driver.session.return_value.__enter__.return_value = session
    driver.session.return_value.__exit__.return_value = None
    return driver


@pytest.fixture
def mock_graph_provider():
    """Mock GraphProvider."""
    provider = AsyncMock()
    session = AsyncMock()
    provider.session.return_value.__aenter__.return_value = session
    provider.session.return_value.__aexit__.return_value = None
    return provider


class TestRuleUpsertManagerInit:
    """Test RuleUpsertManager initialization."""

    def test_init_with_driver(self, mock_graph_driver):
        """Test initialization with sync driver."""
        manager = RuleUpsertManager(graph=mock_graph_driver)
        assert manager._graph == mock_graph_driver

    def test_init_with_provider(self, mock_graph_provider):
        """Test initialization with async provider."""
        manager = RuleUpsertManager(graph_provider=mock_graph_provider)
        assert manager._graph_provider == mock_graph_provider


class TestUpsertAutoGeneratedRules:
    """Test upsert_auto_generated_rules method."""

    def test_upsert_creates_batch_id_if_not_provided(self, mock_graph_driver):
        """Test that batch_id is auto-generated if not provided."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.return_value = []

        manager = RuleUpsertManager(graph=mock_graph_driver)
        patterns = [{"id": "r1", "rule": "Test rule", "type_hint": "test"}]

        result = manager.upsert_auto_generated_rules(patterns)

        assert result["batch_id"].startswith("batch_")

    def test_upsert_creates_rules(self, mock_graph_driver):
        """Test upserting rules creates Rule nodes."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.return_value = []

        manager = RuleUpsertManager(graph=mock_graph_driver)
        patterns = [
            {"id": "r1", "rule": "Test rule 1", "type_hint": "explanation"},
            {"id": "r2", "rule": "Test rule 2", "type_hint": "summary"},
        ]

        result = manager.upsert_auto_generated_rules(patterns, batch_id="test_batch")

        assert result["success"] is True
        assert result["created"]["rules"] == 2

    def test_upsert_creates_constraints(self, mock_graph_driver):
        """Test upserting rules with constraints."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.return_value = []

        manager = RuleUpsertManager(graph=mock_graph_driver)
        patterns = [
            {
                "id": "r1",
                "rule": "Test rule",
                "type_hint": "test",
                "constraint": "Must be under 100 words",
            }
        ]

        result = manager.upsert_auto_generated_rules(patterns, batch_id="test_batch")

        assert result["created"]["constraints"] == 1

    def test_upsert_creates_best_practices(self, mock_graph_driver):
        """Test upserting rules with best practices."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.return_value = []

        manager = RuleUpsertManager(graph=mock_graph_driver)
        patterns = [
            {
                "id": "r1",
                "rule": "Test rule",
                "type_hint": "test",
                "best_practice": "Always cite sources",
            }
        ]

        result = manager.upsert_auto_generated_rules(patterns, batch_id="test_batch")

        assert result["created"]["best_practices"] == 1

    def test_upsert_creates_examples(self, mock_graph_driver):
        """Test upserting rules with examples."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.return_value = []

        manager = RuleUpsertManager(graph=mock_graph_driver)
        patterns = [
            {
                "id": "r1",
                "rule": "Test rule",
                "type_hint": "test",
                "example_before": "Bad example",
                "example_after": "Good example",
            }
        ]

        result = manager.upsert_auto_generated_rules(patterns, batch_id="test_batch")

        assert result["created"]["examples"] == 1

    def test_upsert_handles_invalid_patterns(self, mock_graph_driver):
        """Test upsert handles invalid patterns gracefully."""
        session = mock_graph_driver.session.return_value.__enter__.return_value

        manager = RuleUpsertManager(graph=mock_graph_driver)
        patterns = [
            {"id": "r1"},  # Missing 'rule' field
            {"rule": "Test"},  # Missing 'id' field
        ]

        result = manager.upsert_auto_generated_rules(patterns, batch_id="test_batch")

        assert len(result["errors"]) == 2
        assert result["created"]["rules"] == 0

    def test_upsert_handles_exceptions(self, mock_graph_driver):
        """Test upsert handles exceptions during processing."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.side_effect = Exception("Database error")

        manager = RuleUpsertManager(graph=mock_graph_driver)
        patterns = [{"id": "r1", "rule": "Test", "type_hint": "test"}]

        result = manager.upsert_auto_generated_rules(patterns, batch_id="test_batch")

        assert result["success"] is False
        assert len(result["errors"]) > 0


class TestUpsertRuleNode:
    """Test _upsert_rule_node method."""

    def test_upsert_rule_node_creates_new(self, mock_graph_driver):
        """Test upserting new rule node."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.return_value = []  # Empty = new node

        manager = RuleUpsertManager(graph=mock_graph_driver)
        result = manager._upsert_rule_node(
            rule_id="r1",
            description="Test rule",
            type_hint="explanation",
            batch_id="batch_1",
            timestamp="2024-01-01T00:00:00Z",
        )

        assert result["created"] is True

    def test_upsert_rule_node_updates_existing(self, mock_graph_driver):
        """Test upserting existing rule node."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.return_value = [{"existing_batch_id": "old_batch"}]

        manager = RuleUpsertManager(graph=mock_graph_driver)
        result = manager._upsert_rule_node(
            rule_id="r1",
            description="Updated rule",
            type_hint="explanation",
            batch_id="batch_2",
            timestamp="2024-01-02T00:00:00Z",
        )

        assert result["created"] is False

    def test_upsert_rule_node_requires_driver_when_no_provider(self):
        """Test that upsert_rule_node requires driver when no provider."""
        manager = RuleUpsertManager(graph=None, graph_provider=None)

        with pytest.raises(ValueError, match="Graph driver must be initialized"):
            manager._upsert_rule_node(
                rule_id="r1",
                description="Test",
                type_hint="test",
                batch_id="batch_1",
                timestamp="2024-01-01T00:00:00Z",
            )


class TestUpsertConstraintNode:
    """Test _upsert_constraint_node method."""

    def test_upsert_constraint_creates_and_links(self, mock_graph_driver):
        """Test upserting constraint creates node and links to rule."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.return_value = []

        manager = RuleUpsertManager(graph=mock_graph_driver)
        result = manager._upsert_constraint_node(
            constraint_id="c1",
            description="Test constraint",
            rule_id="r1",
            batch_id="batch_1",
            timestamp="2024-01-01T00:00:00Z",
        )

        assert result["created"] is True
        assert session.run.call_count == 2  # Check + upsert


class TestGetRulesByBatchId:
    """Test get_rules_by_batch_id method."""

    def test_get_rules_by_batch_id(self, mock_graph_driver):
        """Test retrieving rules by batch ID."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.return_value = [
            {"labels": ["Rule"], "id": "r1", "created_at": "2024-01-01T00:00:00Z"},
            {"labels": ["Constraint"], "id": "c1", "created_at": "2024-01-01T00:00:00Z"},
        ]

        manager = RuleUpsertManager(graph=mock_graph_driver)
        rules = manager.get_rules_by_batch_id("batch_1")

        assert len(rules) == 2
        assert rules[0]["id"] == "r1"


class TestRollbackBatch:
    """Test rollback_batch method."""

    def test_rollback_batch_deletes_nodes(self, mock_graph_driver):
        """Test rollback deletes all nodes in batch."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.side_effect = [
            [{"cnt": 5}],  # Count query
            None,  # Delete query
        ]

        manager = RuleUpsertManager(graph=mock_graph_driver)
        result = manager.rollback_batch("batch_1")

        assert result["success"] is True
        assert result["deleted_count"] == 5

    def test_rollback_batch_handles_empty_batch(self, mock_graph_driver):
        """Test rollback handles empty batch gracefully."""
        session = mock_graph_driver.session.return_value.__enter__.return_value
        session.run.side_effect = [
            [{"cnt": 0}],  # No nodes
            None,
        ]

        manager = RuleUpsertManager(graph=mock_graph_driver)
        result = manager.rollback_batch("nonexistent_batch")

        assert result["success"] is True
        assert result["deleted_count"] == 0


class TestAsyncProvider:
    """Test async provider code paths."""

    def test_upsert_with_async_provider(self, mock_graph_provider):
        """Test upserting rules with async provider."""
        session = mock_graph_provider.session.return_value.__aenter__.return_value

        async def mock_run(*args, **kwargs):
            return AsyncMock()

        session.run = mock_run

        manager = RuleUpsertManager(graph=None, graph_provider=mock_graph_provider)
        patterns = [{"id": "r1", "rule": "Test", "type_hint": "test"}]

        with patch("src.qa.graph.rule_upsert.run_async_safely") as mock_run_async:
            mock_run_async.side_effect = lambda coro: {"created": True}

            result = manager.upsert_auto_generated_rules(patterns, batch_id="batch_1")

            # Async path should have been used
            assert mock_run_async.called
